<?php
return [
    'action_not_allowed'             => 'Action NON autorisée (autorisation refusée)',
    'your_system_is_up_to_date'      => 'Votre système est à jour',
    'update_found'                   => 'Mise à jour trouvée',
    'current_version'                => 'Version actuelle',
    'downloading_update'             => 'Téléchargement de la mise à jour....',
    'error_during_download'          => 'Erreur lors du téléchargement.',
    'ok'                             => 'OK',
    'maintenance_mode_activated'     => 'Mode maintenance activé',
    'maintenance_mode_deactivated'   => 'Mode maintenance désactivé',
    'database_migrated'              => 'Migrations de bases de données réussies',
    'system_updated_to_version'      => 'Système mis à jour vers la version',
    'error_during_update'            => 'Erreur lors de la mise à jour (!! vérifier l\'archive de mise à jour !!) --ESSAYER de restaurer le statut OLD........... ',
    'changelog'                      => 'Changelog',
    'directory'                      => 'Dossier',
    'file'                           => 'Fichier',
    'commands_successfully_executed' => 'Commandes exécutées avec succès.',
    'error_during_command_execution' => ' Erreur lors de l\'exécution des commandes.',
    'could_not_save_update'          => 'Impossible d\'enregistrer la nouvelle mise à jour (Vérifiez les permissions d\'écriture /storage/app/tmp/). Mise à jour annulée.',
    'failed'                         => 'Échoué',
    'backup_folder_located_in'       => 'Le dossier de sauvegarde se trouve dans:',
    'restore_system_command'         => 'Désactiver le mode maintenance manuellement en utilisant',
    'restored'                       => 'Restauré',
    'Update_Now'                     => 'Mettre à jour maintenant',
    'Update_Available'               => 'Mise à jour disponible',
    'Updated'                        => 'Mis à jour',
    'Updating'                       => 'Mis à jour en cours',
    'error_try_again'                => 'Erreur. Essayez encore',
];
